### ISSUE TITLE
TODO For Version 10 release

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Suite#85]
- [ ] Update documentation on gitbook to have latest == v10
- [ ] Publish packages to nuget (ospsuite.xxxx)
- [ ] New release of 3 bespoke models
- [ ] Qualification reports (https://github.com/Open-Systems-Pharmacology/OSP-Qualification-Reports)
- [ ] Model evaluation reports (https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library)
- [ ] Batch comparison (@Yuri05  to send the filter to use)
- [ ] Update the IntegrationTests in Ranorex

**Comment by Yuri05** [comment]
@msevestre Added to the TODO list
- [ ] Release of Qualification Runner 10
